import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';
  import 'react-toastify/dist/ReactToastify.css';

import './globals.css';
import { ToastContainer } from 'react-toastify';

const quicksand = Quicksand({ subsets: ['latin'], weight: ['400', '500', '600', '700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${quicksand.className} text-[#999]`}>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
